"""empty message

Revision ID: 32eb05e8df2b
Revises: 9308da92e05b
Create Date: 2023-08-25 10:11:13.290662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eb05e8df2b'
down_revision = '9308da92e05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_constraint('fk_games_game_id_games', type_='foreignkey')
        batch_op.drop_constraint('fk_games_user_id_users', type_='foreignkey')
        batch_op.drop_column('game_id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_user_id_users'), 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_game_id_games'), 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_game_id_games'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('game_id')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_games_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_games_game_id_games', 'games', ['game_id'], ['id'])

    # ### end Alembic commands ###
