"""validate reviews

Revision ID: 4c6aefafb822
Revises: 32eb05e8df2b
Create Date: 2023-08-29 12:47:43.263861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6aefafb822'
down_revision = '32eb05e8df2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('_user_game_unique_constraint', ['user_id', 'game_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('_user_game_unique_constraint', type_='unique')

    # ### end Alembic commands ###
